### ISSUE TITLE
Meta Description disappearing 

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-banners#7]
**Describe the bug**
If I turn on the option for Dynamic title on the Event Calendar option from the theme options, the meta information disappears on the body of each event on the archive page of the event (on list view, month view and calendar view). If I disable this option, the meta works fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Theme Options -> Tribe Event Options
2. Check the Dynamic Title Option
3. Save
4. See error on the Calendar Archive page

**Expected behaviour**
This change should only affect the banner, not the list of events on the body.

**Screenshots**

With the option 'on'
![Screen Shot 2019-10-30 at 11 22 33 AM](https://user-images.githubusercontent.com/3129483/67866368-9bdff780-fb07-11e9-83a3-f38beb849b47.png)

With the option 'off'
![Screen Shot 2019-10-30 at 11 24 13 AM](https://user-images.githubusercontent.com/3129483/67866542-dfd2fc80-fb07-11e9-989a-b4184e884506.png)

**Desktop (please complete the following information):**
 - sHappening in all browsers

**Mobile (please complete the following information):**
 - Happening in device

**Comment by krugazul** [comment]
@viscosho I have removed the title function which was disabling the post meta.
![Screenshot 2019-12-18 at 17 38 13](https://user-images.githubusercontent.com/1805603/71100184-39c57980-21bd-11ea-9cf4-69235959df03.png)
