### ISSUE TITLE
This banner image needs to work, even if there is no feature image

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-banners#9]
**Describe the bug**
This banner image needs to work, even if there is no feature image 

**To Reproduce**
This happens when lsx banners is on.
1. Go to Theme Options
2. Click on Tribe events
3. Add a default image for the banner

**Expected behavior**
The banner image needs to work, even if there is no feature image, with the banners plugin on.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3129483/70823423-9e986280-1dbe-11ea-97e1-5f68084ea2ff.jpg)

**Reference**
[https://www.bugherd.com/projects/97685/tasks/363](https://www.bugherd.com/projects/97685/tasks/363)

**Comment by krugazul** [comment]
![Screenshot 2020-03-31 at 10 16 07](https://user-images.githubusercontent.com/1805603/78003701-60a55700-7339-11ea-96f3-02f1915b9b15.png)
